# -*- coding: utf-8 -*-
"""multiple_linear_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xrtVJcBfu5gT18pI4hiKLx3fzlAKpnk0

# Multiple Linear Regression

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
pd.options.display.float_format = '{:.5f}'.format

"""## Importing the dataset and Splitting the training and test set"""

train_dataset = pd.read_csv('Train.csv')
test_dataset = pd.read_csv('Test.csv')

X_train = train_dataset.iloc[:, :-1].values
y_train = train_dataset.iloc[:, -1].values
X_test = test_dataset.iloc[:].values

print(X_train)

print(y_train)

print(X_test)

"""## Training the Multiple Linear Regression model on the Training set"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = regressor.predict(X_test)
print(y_pred.reshape(len(y_pred),1))

